// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsSgjaksps8CExrB7CjVBnzb_OPMeqPOs',
    appId: '1:209239423699:web:88705825d78c2a6ea93226',
    messagingSenderId: '209239423699',
    projectId: 'myfirebaseapp02-90488',
    authDomain: 'myfirebaseapp02-90488.firebaseapp.com',
    storageBucket: 'myfirebaseapp02-90488.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOOE0bYrAILCY877rri2XCOST80g9qXzQ',
    appId: '1:209239423699:android:5f6900be32a68f24a93226',
    messagingSenderId: '209239423699',
    projectId: 'myfirebaseapp02-90488',
    storageBucket: 'myfirebaseapp02-90488.appspot.com',
  );
}
